PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX hawkesbury: <https://linked.data.gov.au/dataset/floods/hawkesbury-2021>
SELECT DISTINCT ?iri ?id ?lbl ?class ?data_value
WHERE {
    BIND (hawkesbury: AS ?entity)
    VALUES ?knownClass { prov:Activity prov:Entity provwf:Block }
    VALUES ?workflow {pwfs:a7a99e2f-0971-11ed-bee3-8b1d5e0c55d6}
    {
        ?workflow provwf:hadBlock ?block .
        ?block a ?class_ .
        OPTIONAL {?block rdfs:label ?label .}
        BIND(COALESCE(?label, "missing label") AS ?lbl)
        BIND("" AS ?data_value)
        BIND(?block as ?iri)
        BIND (STRAFTER(STR(?block), "https://data.surroundaustralia.com/dataset/provworkflows/") AS ?id)
        BIND (STRAFTER(STR(?class_), STR(provwf:)) AS ?class)
    }
    UNION
    {
        # block's used entities
        ?workflow provwf:hadBlock ?block .
        ?block prov:used ?iri .
        ?iri rdfs:label ?lbl ;
        a ?class_ ;
        prov:value ?data_value
        BIND (STRAFTER(STR(?iri), STR(pwfs:)) AS ?id)
        BIND (STRAFTER(STR(?class_), STR(prov:)) AS ?class)
    }
    UNION
    {
        # block's generated entities
        ?workflow provwf:hadBlock ?block .
        ?block prov:generated ?iri .
        ?iri rdfs:label ?lbl ;
        a ?class_ ;
        prov:value ?data_value
        BIND (STRAFTER(STR(?iri), STR(pwfs:)) AS ?id)
        BIND (STRAFTER(STR(?class_), STR(prov:)) AS ?class)
    }
    FILTER (?class_ IN (?knownClass))
}
ORDER BY DESC(?eat)