PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT DISTINCT ?source ?target ?linkClass
WHERE {
    BIND (hawkesbury: AS ?entity)
    {
        ?versionedEntity prov:wasRevisionOf ?entity .
        BIND (?versionedEntity AS ?source)
        BIND (hawkesbury: AS ?target)
        BIND (prov:wasRevisionOf AS ?linkClass)
    }
    UNION
    {
        ?workflow prov:generated ?versionedEntity .
        ?versionedEntity prov:wasRevisionOf ?entity .
        BIND (?workflow AS ?source)
        BIND (?versionedEntity AS ?target)
        BIND (prov:generated AS ?linkClass)
    }
}
ORDER BY DESC(?eat)